// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                     pgtype.UUID
	Email                  string
	ProfilePicture         pgtype.Text
	EmailVerified          bool
	EmailVerificationToken pgtype.Text
	PasswordHash           string
	RefreshToken           pgtype.Text
	RefreshTokenExpiresAt  pgtype.Timestamp
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
}
